steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Нужен полный доступ к истории для сброса

      - name: Reset Damaged Project
        run: |
          git fetch origin main
          git checkout origin/main -- network.xcodeproj/
          echo "Project file has been reset to original state."
